title: Amit Singh
url: "https://amits1ngh.github.io"
baseurl: "https://amits1ngh.github.io"

markdown: kramdown
# twitter_username: 
tracking_id: UA-108355039-1

collections:
  - projects

paginate: false

sass:
    style: compressed
    sass_dir: _sass
